name: 'Setup Docker Action'
description: 'Action to setup and log you into your Docker registry'
author: 'Bryan Clark'
inputs:
  username:
    description: 'username for docker registry'
  password:
    description: 'password or token for docker registry'
  registry:
    description: 'domain name for the docker registry, e.g. docker.pkg.github.com'
    default: 'docker.pkg.github.com'
  experimental:
    description: 'turn on experimental docker client features'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'