name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # build: # make sure build/ci work properly
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - run: |
  #       npm install
  #       npm run all
  test: # make sure the action works on a clean machine without building
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest] #, windows-latest, ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: https://docker.pkg.github.com
    - name: debug
      if: ${{ always() }}
      run: |
        ls -R /Users/runner/hostedtoolcache/docker/
        echo $PATH

